name: Fetch Number Example

on:
  push:
    branches:
      - master

jobs:
  fetch-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Add Mask
        run: echo "::add-mask::${{ secrets.GH_SECRET }}"

      - name: Fetch Number
        id: fetch
        run: echo "myNumber=$(node numbers.js)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set GitHub Secret
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/ORG/actions/secrets/public-key)
          echo "Response: $response"

      # - name: Check length of the Secret
      #   run: |
      #     GH_SECRET="${{ secrets.GH_SECRET }}"
      #     echo "GH_SECRET length: ${#GH_SECRET}"
        