name: Fetch Number Example

on:
  push:
    branches:
      - master

jobs:
  fetch-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set env variable to secret
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.GH_SECRET }}
        run: |
          example-command "$SUPER_SECRET"

      - name: Add Mask
        run: echo "::add-mask::$SUPER_SECRET"

      - name: Fetch Number
        id: fetch
        run: echo "myNumber=$(node numbers.js)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set GitHub Secret
        run: echo "MY_NUMBER=${{ steps.fetch.outputs.myNumber }}" >> $SUPER_SECRET

      - name: Check length of the Secret
        run: |
          GH_SECRET="${{ secrets.GH_SECRET }}"
          echo "GH_SECRET length: ${#GH_SECRET}"
        