name: Fetch Number Example

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  fetch-number:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up PAT token
        env:
          PAT_TOKEN: ${{ secrets.GH_PAT }}
        run: echo $PAT_TOKEN

      - name: Fetch Number
        id: fetch
        run: echo "myNumber=$(node numbers.js)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set GitHub Secret
        run: |
          response=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PAT_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/ngunner15/actions/secrets/public-key)
          echo "Response: $response"
        